# numpy

---
**author:** 刘志强

**mail:**   liuzhiqiang182@mails.ucas.ac.cn

**time:**   2019/4/2

*互相学习，互相进步*

---

## (1) ndarry (N-dimensinal array)

In [18]:
import numpy as np

In [6]:
######define a 1-D array######
a1=np.array([1,2,3])
a2=np.array([[1,2,3]])
print a1
print a2

[1 2 3]
[[1 2 3]]


In [26]:
#check the attribute of 'a'
print 'data framework is:',type(a1)
print 'the data type for a1 is:',a1.dtype
print 'the rank is: ',a1.ndim
print 'the size is:',a1.size
print 'the shape is:',a1.shape
print 'the shape is:',a2.shape

data framework is: <type 'numpy.ndarray'>
the data typeis: int64
the rank is:  1
the size is: 3
the shape is: (3,)
the shape is: (1, 3)


In [30]:
######define a 2-D array######
b1=np.array([[1.2,1.4],[0.3,0.5]],dtype=complex)
b2=np.array([['a','b'],['c','d']])
print b1
print b2

[[1.2+0.j 1.4+0.j]
 [0.3+0.j 0.5+0.j]]
[['a' 'b']
 ['c' 'd']]


In [31]:
#check the attribute of 'b'
print 'the data type for b1 is:',b1.dtype
print 'the data type for b2 is:',b2.dtype
print 'the rank is: ',b1.ndim
print 'the size is:',b1.size
print 'the shape is:',b1.shape

the data type for b1 is: complex128
the data type for b2 is: |S1
the rank is:  2
the size is: 4
the shape is: (2, 2)


In [64]:
######create array######
print np.zeros((3,3))
print np.ones((3,3))
print np.random.random((3,3))
print '--------------------------'
print np.arange(4)
print np.arange(4,10)
print np.arange(1,12,3)
print np.arange(0,6,0.6)
print np.arange(0,12).reshape(3,4)
print '--------------------------'
print np.linspace(0,10,5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.21078938 0.99792321 0.7429291 ]
 [0.49712004 0.59903499 0.98643779]
 [0.06134171 0.95172967 0.63636694]]
--------------------------
[0 1 2 3]
[4 5 6 7 8 9]
[ 1  4  7 10]
[0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------
[ 0.   2.5  5.   7.5 10. ]


## (2) 代数矩阵运算

In [46]:
######element operation#######
a1=np.arange(4,8)
a2=np.arange(4)
print a1
print a2
print '------------------'
print a1+4
print a1*2
print a1+a2
print a1*a2
print '------------------'
print a1*np.sin(a2)

[4 5 6 7]
[0 1 2 3]
------------------
[ 8  9 10 11]
[ 8 10 12 14]
[ 4  6  8 10]
[ 0  5 12 21]
------------------
[0.         4.20735492 5.45578456 0.98784006]


In [56]:
A=np.arange(0,9).reshape(3,3)
B=np.array([[1,2,3],[2,5,9],[9,4,2]])
print A*B

[[ 0  2  6]
 [ 6 20 45]
 [54 28 16]]


In [63]:
######matrix operation######
print np.dot(A,B)
print A.dot(B)
print np.dot(B,A)
print '---------------------'
print np.linalg.inv(B)
e,v=np.linalg.eig(B)
print '---------------------'
print e
print v
print np.diag(e)
print '---------------------'
print np.linalg.pinv(A)

[[20 13 13]
 [56 46 55]
 [92 79 97]]
[[20 13 13]
 [56 46 55]
 [92 79 97]]
[[ 24  30  36]
 [ 69  85 101]
 [ 24  39  54]]
---------------------
[[-1.52941176  0.47058824  0.17647059]
 [ 4.52941176 -1.47058824 -0.17647059]
 [-2.17647059  0.82352941  0.05882353]]
---------------------
[12.20928637 -0.36190391 -3.84738246]
[[-0.28829306 -0.26117461 -0.15593447]
 [-0.77757905  0.85368797 -0.68685997]
 [-0.55880044 -0.4505604   0.70986465]]
[[12.20928637  0.          0.        ]
 [ 0.         -0.36190391  0.        ]
 [ 0.          0.         -3.84738246]]
---------------------
[[-5.55555556e-01 -1.66666667e-01  2.22222222e-01]
 [-5.55555556e-02  1.83880688e-16  5.55555556e-02]
 [ 4.44444444e-01  1.66666667e-01 -1.11111111e-01]]


In [66]:
######aggregation function######
print A
print A.sum()
print A.min()
print A.max()
print a.mean()
print a.std()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
0
8
2.0
0.816496580927726


## (3) 索引、切片、迭代

In [69]:
######index######
a=np.arange(10,16)
print a
print a[0],a[1],a[-1],a[-2]
print a[[1,3,4]]

[10 11 12 13 14 15]
10 11 15 14
[11 13 14]


In [73]:
######section######
A=np.arange(10,19).reshape((3,3))
print a[1:5]
print a[1:5:2]
print a[::2]
print a[:5:2]
print a[:5:]
print '-------------------'
print A
print A[0,:]
print A[0:2,0:2]
print A[[0,2],0:2]

[11 12 13 14]
[11 13]
[10 12 14]
[10 12 14]
[10 11 12 13 14]
-------------------
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[10 11 12]
[[10 11]
 [13 14]]
[[10 11]
 [16 17]]


In [81]:
######iteration######
for i in a:
    print i
for row in A:
    print row
for item in A.flat:
    print item
print '-------------------'    
print np.apply_along_axis(np.mean,axis=0,arr=A)
print np.apply_along_axis(np.mean,axis=1,arr=A)
print '-------------------'
def f(x):
    return x/2
print np.apply_along_axis(f,axis=1,arr=A)
print np.apply_along_axis(f,axis=0,arr=A)

10
11
12
13
14
15
[10 11 12]
[13 14 15]
[16 17 18]
10
11
12
13
14
15
16
17
18
-------------------
[13. 14. 15.]
[11. 14. 17.]
-------------------
[[5 5 6]
 [6 7 7]
 [8 8 9]]
[[5 5 6]
 [6 7 7]
 [8 8 9]]


## (4) 条件

In [84]:
A=np.random.random((4,4))
print A<0.5
print A[A<0.5]

[[False False False False]
 [False False  True False]
 [ True  True  True False]
 [ True  True False  True]]
[0.11192502 0.03210371 0.37951122 0.35511741 0.15791806 0.18274546
 0.17341374]


## (5) 形状改变

In [88]:
a=np.random.random(12)
print 'initial vector "a"',a
A=a.reshape(3,4)
a.shape=(3,4)
print '----------------'
print 'tansform into 3*4 matrix',a
print '----------------'
print 'back to vector',a.ravel()
a.shape=(12)
print '----------------'
print A.transpose()

initial vector "a" [0.19356155 0.21455872 0.44775613 0.20349479 0.35010934 0.03703813
 0.83740332 0.32814506 0.24217409 0.52875548 0.95675934 0.44882848]
----------------
tansform into 3*4 matrix [[0.19356155 0.21455872 0.44775613 0.20349479]
 [0.35010934 0.03703813 0.83740332 0.32814506]
 [0.24217409 0.52875548 0.95675934 0.44882848]]
----------------
back to vector [0.19356155 0.21455872 0.44775613 0.20349479 0.35010934 0.03703813
 0.83740332 0.32814506 0.24217409 0.52875548 0.95675934 0.44882848]
----------------
[[0.19356155 0.35010934 0.24217409]
 [0.21455872 0.03703813 0.52875548]
 [0.44775613 0.83740332 0.95675934]
 [0.20349479 0.32814506 0.44882848]]


## (6) 连接和切分

In [90]:
######joint######
A=np.ones((3,3))
B=np.zeros((3,3))
print np.vstack((A,B))
print np.hstack((A,B))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [92]:
a=np.array([0,1,2])
b=np.array([3,4,5])
c=np.array([6,7,8])
print np.column_stack((a,b,c))
print np.row_stack((a,b,c))

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [98]:
######split######
A=np.arange(16).reshape((4,4))
[B,C]=np.hsplit(A,2)
print A
print B
print C
print '---------------'
[B,C]=np.vsplit(A,2)
print B
print C

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
---------------
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [104]:
[A1,A2,A3]=np.split(A,[1,3],axis=1)
print A1
print A2
print A3

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


## (7) 视图和副本

In [4]:
a=np.array([1,2,3,4])
b=a
print b
a[2]=0
print b

a=np.array([1,2,3,4])
b=a.copy()
print b
a[2]=0
print b

[1 2 3 4]
[1 2 0 4]
[1 2 3 4]
[1 2 3 4]


## (8) Numpy广播机制

In [5]:
A=np.arange(16).reshape(4,4)
b=np.arange(4)
print A+b
m=np.arange(6).reshape(3,1,2)
n=np.arange(6).reshape(3,2,1)
print m+n

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]
[[[ 0  1]
  [ 1  2]]

 [[ 4  5]
  [ 5  6]]

 [[ 8  9]
  [ 9 10]]]


## (9) 结构化数组

In [13]:
s=np.array([(1,'first',0.5,1+2j),(2,'second',1.1,1-1j)],dtype=('i2,a6,f4,c8'))
print np.array([(1,'first',0.5,1+2j),(2,'second',1.1,1-1j)],dtype=('i2,a6,f4,c8'))
print np.array([(1,'first',0.5,1+2j),(2,'second',1.1,1-1j)],dtype=('int16,a6,float32,complex64'))

[(1, 'first', 0.5, 1.+2.j) (2, 'second', 1.1, 1.-1.j)]
[(1, 'first', 0.5, 1.+2.j) (2, 'second', 1.1, 1.-1.j)]


In [17]:
print s[1]
print s['f1']
print s['f2']

(2, 'second', 1.1, 1.-1.j)
['first' 'second']
[0.5 1.1]
